dataset:
    name: dataset:CarImageDataset
    params:
        root_dir: data/
        num_folds: 10
        seed: 42
model:
    name: model:CNNImageScorer
    params:
        img_size: 224
        num_scores: 2
hparams:
    epochs: 1
    batch_size: 16
    lr: 0.001
    criterion:
        name: torch.nn:MSELoss
        params: {}
    optimizer:
        name: torch.optim:Adam
        params:
            lr: 0.001


transform:
    - transforms.Resize(256)
    - transforms.CenterCrop(224)
    - transforms.ToTensor()
    - transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])      